title: Diego Anzolin Ferreira # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software developer at CH Master Data. Always interested in understanding how stuff works and learning new technologies.
  <a href="https://www.linkedin.com/in/diego.anzolin/">View my Linkedin profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-143621465-1 # your Google Analytics tracking ID here
